name: Build and demo testrunner

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.16.x'
          otp-version: '26.x'

      - name: Install dependencies
        run: mix deps.get
      - name: Compile dependencies
        run: mix deps.compile

      - name: Build application
        run: mix compile
      - name: Build escript executable
        run: MIX_ENV=prod mix escript.build

      - name: Print dialyzer info
        run: dialyzer --version && dialyzer

      - name: Print gradualizer info
        run: ./gradualizer --version

      - name: Print ety info # has no version yet
        run: ./ety

      - name: Print eqWAlizer info 
        run: ./elp version

      - name: Execute Runner on test data
        run: out/testrunner -s test-src
      - name: Archive test results

        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test_results.json
