name: Build and demo testrunner

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.16.x'
          otp-version: '25.3.x'

      - name: Install dependencies
        run: mix deps.get
      - name: Compile dependencies
        run: mix deps.compile

      - name: Build application
        run: mix compile
      - name: Build escript executable
        run: MIX_ENV=prod mix escript.build

      - name: Execute Runner on test data
        run: out/testrunner -s test-src
