name: Build testrunner

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1

      - name: Install dependencies
        run: mix deps.get
      - name: Compile dependencies
        run: mix deps.compile

      - name: Build application
        run: mix compile
      - name: Build escript executable
        run: MIX_ENV=prod mix escript.build
